version: '3'

services:
  api:
    user: ${OPEN_GENES_UID}
    build:
      context: .
      dockerfile: Dockerfile
    image: open-genes-backend-dev
    hostname: opengenes-api
    container_name: open-genes-api-dev
    volumes:
      - "./api:/api"
      - "./.env:/.env"
      - "./requirements.txt:/requirements.txt"
    network_mode: "host"

  scripts:
    user: ${OPEN_GENES_UID}
    image: open-genes-backend-dev
    hostname: opengenes-backend
    container_name: open-genes-scripts-dev
    volumes:
      - "./api:/api"
      - "./scripts:/scripts"
      - "./.env:/.env"
      - "./requirements.txt:/requirements.txt"
    network_mode: "host"
    working_dir: /scripts
    command: /bin/bash
