#Workflow for demo environment

name: demo-CI

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build project
        run: bash open-genes.sh prod
      - name: Upload project artifacts
        uses: actions/upload-artifact@v2
        with:
          path: .
          name: project
        
  deploy-demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download project artifacts
        uses: actions/download-artifact@v2
        with:
          name: project
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy with rsync
        run: |
          echo $DROPLET_ENV | base64 -d > .env
          rsync -zhrl -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' . $SSH_USER@$SSH_HOST:$PROJECT_PATH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          PROJECT_PATH: ${{ secrets.PROJECT_DEMO_PATH }}
          DROPLET_ENV: ${{ secrets.DROPLET_DEMO_ENV }}